const contact = {
  userId: 0,
  contactId: 0,
  givenName: '',
  preferredName: '',
  middleName: '',
  familyName: '', 
  maidenName: '',
  gender: '', 
  // photo: {},
  // spouse: {},
  // children: [{}, {}],
  birthYear: 2000,
  birthMonth: 1,
  birthDay: 1,
  phoneNumbers: [{}, {}],
  emails: [{}, {}],
  // address: {},
  // city: {},
  // lastContacted: 'DATE',
  // dateMet: 'DATE',
  // howMet: {},
  // businessCards: [{}],
  // employer: {},
  // industry: {},
  // occupation: '',
  groups: [{}, {}],
  // details: {
  //   interactions: [{}, {}],
  //   notes: [{}, {}],
  //   events: [{}, {}],
  //   lifeEvents: [{}, {}]
  // },
  // preferences: {
  //   colors: [{}, {}],
  //   foods: [{}, {}],
  //   animals: [{}, {}],
  //   locations: [{}, {}],
  //   activites: [{}, {}],
  //   books: [{}, {}],
  //   movies: [{}, {}],
  //   shows: [{}, {}],
  //   styles: [{}, {}],
  //   sportsTeams: [{}, {}],
  // },
  // personalityProfiles: {}
};