const contact = {
  userId: 0,
  contactId: 0,
  photo: {},
  givenName: '',
  preferredName: '',
  middleName: '',
  familyName: '', 
  maidenName: ''
  gender: '', 
  spouse: {},
  // children: [{}, {}],
  birthYear: 2000,
  birthMonth: 1,
  birthDay: 1,
  address: {},
  city: {},
  lastContacted: 'DATE',
  dateMet: 'DATE',
  howMet: {},
  businessCards: [{}],
  phoneNumbers: [{}, {}],
  emails: [{}, {}],
  employer: {},
  industry: {},
  occupation: '',
  groups: [{}, {}],
  details: {
    interactions: [{}, {}],
    notes: [{}, {}],
    events: [{}, {}],
    lifeEvents: [{}, {}]
  },
  preferences: {
    colors: [{}, {}],
    foods: [{}, {}],
    animals: [{}, {}],
    locations: [{}, {}],
    activites: [{}, {}],
    books: [{}, {}],
    movies: [{}, {}],
    shows: [{}, {}],
    styles: [{}, {}],
    sportsTeams: [{}, {}],
  },
  personalityProfiles: {}
};