-- ---
-- HOW TO USE 
-- PIPE THIS FILE INTO YOUR MYSQL DATABASE TO CLEAN THE DB AND TABLES
--
--

-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;


--  DROP DATABASE IF EXISTS devdb001;
--  CREATE DATABASE devdb001;


USE devdb001;


-- ---
-- Table 'contacts'
-- 
-- ---

DROP TABLE IF EXISTS contacts;

CREATE TABLE contacts (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  given_name VARCHAR(255) NOT NULL,
  preferred_name VARCHAR(255) NOT NULL,
  middle_name VARCHAR(255) NULL DEFAULT NULL,
  family_name VARCHAR(255) NOT NULL,
  maiden_name VARCHAR(255) NULL DEFAULT NULL,
  gender VARCHAR(255) NOT NULL,
  birth_year SMALLINT NULL DEFAULT NULL,
  birth_month TINYINT NULL DEFAULT NULL,
  birth_day TINYINT NULL DEFAULT NULL,
  id_city INTEGER NULL DEFAULT NULL,
  id_employer INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'phone_numbers'
-- 
-- ---

DROP TABLE IF EXISTS phone_numbers;

CREATE TABLE phone_numbers (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id_contact INTEGER NOT NULL,
  digits VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'emails'
-- 
-- ---

DROP TABLE IF EXISTS emails;

CREATE TABLE emails (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id_contact INTEGER NOT NULL,
  email_address VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'cities'
-- 
-- ---

DROP TABLE IF EXISTS cities;

CREATE TABLE cities (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  city VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'employers'
-- 
-- ---

DROP TABLE IF EXISTS employers;

CREATE TABLE employers (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  employer VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'groups'
-- 
-- ---

DROP TABLE IF EXISTS groups;

CREATE TABLE groups (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  group VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'people_groups'
-- 
-- ---

DROP TABLE IF EXISTS people_groups;

CREATE TABLE people_groups (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id_contact VARCHAR(255) NULL DEFAULT NULL,
  id_groups VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'interaction_type'
-- 
-- ---

DROP TABLE IF EXISTS interaction_type;

CREATE TABLE interaction_type (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  type VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'interactions'
-- 
-- ---

DROP TABLE IF EXISTS interactions;

CREATE TABLE interactions (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id_contact VARCHAR(255) NULL DEFAULT NULL,
  id_interaction_type VARCHAR(255) NULL DEFAULT NULL,
  desccription MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'notes'
-- 
-- ---

DROP TABLE IF EXISTS notes;

CREATE TABLE notes (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  note VARCHAR(255) NULL DEFAULT NULL,
  id_interaction INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (id)
)


-- ---
-- Table 'photos'
-- 
-- ---

DROP TABLE IF EXISTS photos;

CREATE TABLE photos (
  id INTEGER NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  type VARCHAR(255),
  description TEXT NULL DEFAULT NULL,
  url TEXT NULL DEFAULT NULL,
  PRIMARY KEY (id)
)