INSERT INTO `cities` (`created_at`, `updated_at`, `city`) VALUES
(NOW(), NOW(), 'Honolulu'),
(NOW(), NOW(), 'San Diego'),
(NOW(), NOW(), 'Seattle'),
(NOW(), NOW(), 'Austin'),
(NOW(), NOW(), 'San Francisco'),
(NOW(), NOW(), 'San Mateo'),
(NOW(), NOW(), 'Fremont'),
(NOW(), NOW(), 'Phoenix'),
(NOW(), NOW(), 'San Antonio'),
(NOW(), NOW(), 'Monterey Park'),
(NOW(), NOW(), 'Pflugerville'),
(NOW(), NOW(), 'Sacramento'),
(NOW(), NOW(), 'Dana Point'),
(NOW(), NOW(), 'New York City'),
(NOW(), NOW(), 'Los Angeles'),
(NOW(), NOW(), 'Chicago'),
(NOW(), NOW(), 'Union City'),
(NOW(), NOW(), 'Vancouver'),
(NOW(), NOW(), 'Las Vegas');
